const routes ={

    loginRouter:"/user/login",
    registerRouter:"/user/register",
    homeRouter:"/",
    googleRouter:"/google",
    googleCallback:"/google/callback",
    failedAuth: "/failedAuth",
    good:"/good",
    dashboard:"/dashboard",
    profile:"/profile",
    logout:"/logout",
    forgotPassword:"/forgot-password",
    resetPasswordGet:"/reset-password/:id/:token",
    // resetPassword2:"/reset-password/:id/:token",
    // resetPassword2:"/reset-password/:id/:token",
    resetPassword2:"/reset-password/:id/:token",
    resetPassword:"/reset-password",
    temporaryToken:"/temporary-token",
    uploadProduct:"/product/post",
    getallPost:"/posts/:number/:call",
    postInfo:"/post/info/:id",
    uploadPost:"/post/upload",
    likePost:"/post/like/:id",
    deletePost:"/post/:id",
    subscribeUser:"/subscribe/:id",
    getPosts:"/getPosts",
    searchRouter:"/search/:data",
    poolDesign:"/pooldesign/:productId",
    getAllProduct:"/getAllProducts/:number/:call",
    productInfo:"/product/info/:id",
    likeProduct:"/product/like/:id",
    getLikedProducts:"/getLikedProducts",
    getLikedPosts:"/getLikedPosts",
    addtoWishlist:"/addToWishlist/:id",
    removeFromWishlist:"/removeFromWishlist/:id",
    getWishlistByListName:"/getWishlistByListName/:listName",
    postReviewProduct:"/postReviewProduct/:id",
    addRatingProduct:"/postRatingProduct/:id/:rating",
    getReviewProduct:"/getReviewProduct/:id",
    getPooledDesign:"/getPooledDesign",
    getWishlist:"/getWishlist",
    getUserInfo:"/getUserInfo",
    getProductHashtag:"/getProductsHashtag/:hashtag",
    getUserProducts:"/getUserProducts",
    setDeliveryAddress:"/user/setDeliveryAddress",
    placeOrder:"/placeOrder/:productId/:quantity/:colour/:fabric",
    removeOrder:"/removeOrder/:orderId",
    getCanceledProducts:"/getCanceledProducts",
   
   
   
   
    myOrders:"/myOrders",
    getSuccessfulOrders:"/getSuccessfulOrders",
   
   
   
   
    setCategory:"/setCategory",
    getAllCategories:"/getAllCategories",
    upload3d:"/upload3d",
    uploadZigy:"/uploadZigy",
    getUserPosts:"/getUserPosts",
    getUserFollowing:"/getUserFollowing",
    getUserFollowers:"/getUserFollowers",
    getAllPooledDesigns:"/getAllPooledDesigns",
    getOtherUserInfo:"/getOtherUserInfo/:uid",
    // addToCart:"/addToCart/:productid/:size/:colour/:quantity",
    removefromCart: "/removefromCart/:productId",
    getCart:"/getCart/:userId",
    // getCart:"/getCart/:userId",
    getDeliveryAddress: "/getDeliveryAddress",
    removeAddressById: "/removeAddress",
    postRatingProduct: "/postRatingProduct/:id",
    getRatingProduct: "/getRatingProduct/:id",
    // checkout: "/checkout",
    // paymentVerification: "/paymentVerification"
    razorpay: "/razorpay",
    orderpost: "/api/payment/order",
    verifypost:"/api/payment/verify",
    razorpaykey : "/razorpaykey",
    getOtherUserPostsandProducts:"/getOtherUserPostsandProducts/:id",
    getupdateproduct:"/getupdateproduct/:productId/:size/:colour",
    removeFiles:"/removeFiles",
    addUserFollowing:"/addUserFollowing/:id",
    savedDesign:"/savedDesign/:id",
    unSaveDesign:"/unSaveDesign/:id",
    uploadProfilePicture:"/story/uploadProfilePicture",
    getUserProfile:"/getprofilePicture",
    getallProfileImages:"/getallProfileImages/:userId",
    searchProduct:"/searchProduct/:key",
    searchPost:"/searchPost/:key",
    searchUser:"/searchUser/:key",
    reportPost:"/reportPost/:postId",
    hidePost:"/hidePost/:postId",
    favorites:"/favorites/:id",
    topHashtagsforPosts:"/topHashtagsforPosts",
    topHashtagsforProducts:"/topHashtagsforProducts",
    productDetails:"/productDetails/:productId",
    postDetails:"/postDetails/:postId",
    createPool:"/createPool",
    activePool:"/activePool",
    joinPool:"/joinPool/:poolId",
    statusPool:"/statusPool/:poolId",
    closePool:"/closePool/:poolId",
    detailsOfPool:"/detailsOfPool/:poolId",
    imagesOfPooledProducts:"/imagesOfPooledProducts",
    topcloth_categoryforProducts:"/topcloth_categoryforProducts",
    // uploadShopPagePosters:"/uploadShopPagePosters",
    // adminRouter:"/uploadImagesByAdmin"
    getImagesByAdmin:"/getImagesByAdmin",
    searchHashtag:"/searchHashtag/:key",
    recommendedtopcloth_categoryforProducts:"/recommendedtopcloth_categoryforProducts",
    userDetails:"/userDetails/:userId",
    unFollow:"/unFollow/:id",
    getFollowingsInfo:"/getFollowingsInfo/:userId",
    getFollowersInfo:"/getFollowersInfo/:userId",
    getColorFabricSizeOfProduct:"/getColorFabricSizeOfProduct/:productId",
    getAllDesignsScreenshot:"/getAllDesignsScreenshot",
    uploadingPost:"/uploadingPost",
    getApparelsOfDesigns:"/getApparelsOfDesigns",
    userFollowingFollowersCount:"/userFollowingFollowersCount/:userId",
    featured_recommended_products:"/getProducts/:type",
    addCommentsToPost:"/posts/:postId/comments",
    getComments:"/getComments/:postId",
    updateUser:"/updateUser/:userId",
    detailUser:"/detailUser/:userId",
    support:"/support",
    createdPostsAndSavedDesigns:"/createdPostsAndSavedDesigns/:userId",
    updatePoolSuccessFail:"/updatePoolSuccessFail/:poolId",
    
    
    
    
    successRate:"/successRate/:designerId",
    likeAndUnlikeComment:"/likeAndUnlikeComment/:id/:commentId",
    // likeAndUnlikeComment:"/likeAndUnlikeComment/:id/:commentId",
    productFavorites:"/productFavorites/:productId",
    addressOfUser:"/addressOfUser/:userId",
    addAddress:"/addAddress",
    createLinkedAccount:"/createLinkedAccount",
    transfers:"/transfers",
    addtocart:"/addtocart",
    removefromcart:"/removefromcart",
    getAllCartProducts:"/getAllCartProducts/:userId",
    getSavedDesigns:"/getSavedDesigns/:userId",
    addCoupon:"/addCoupon",
    applyCoupon:"/applyCoupon",
    getAllCoupons:"/getAllCoupons",
    getFollowersAndFollowingInfo:"/getFollowersAndFollowingInfo/:userId",
    likeComment:"/likeComment",
    followAndUnfollowUser:"/followAndUnfollowUser/:userId",
    addReview:"/addReview/:productId",
    
    // uploadStory:"/story"
}

module.exports= routes;
